
USE EVENTOS;


CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	idFuncionario INT NOT NULL AUTO_INCREMENT,
    cpfFuncionario VARCHAR(13) NOT NULL,
    nomeFuncionario VARCHAR(60) NOT NULL,
	cargo VARCHAR(50) NOT NULL,
	salarioMensal DECIMAL(7,2) NOT NULL,
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY(idFuncionario)
);


CREATE TABLE IF NOT EXISTS SALAO(
	idSalao INT NOT NULL AUTO_INCREMENT,
    nomeSalao VARCHAR(50) NOT NULL,
    CONSTRAINT SALAO_PK PRIMARY KEY(idSalao)
);

 
CREATE TABLE IF NOT EXISTS EVENTO(
	idEvento INT NOT NULL  AUTO_INCREMENT,
    tipoEvento VARCHAR(50) NOT NULL,
    dataHora DATETIME NOT NULL,
    idSalao INT NOT NULL,
    CONSTRAINT EVENTO_PK PRIMARY KEY(idEvento),
    CONSTRAINT SALAO_FK FOREIGN KEY(idSalao)
		REFERENCES SALAO(idSalao)
);


CREATE TABLE IF NOT EXISTS CLIENTE(
	idCliente INT NOT NULL AUTO_INCREMENT,
    cpfCliente VARCHAR(13) NOT NULL,
    nomeCliente VARCHAR(60) NOT NULL,
	emailCliente VARCHAR(50) NOT NULL,
	CONSTRAINT CLIENTE_PK PRIMARY KEY(idCliente)
);

CREATE TABLE IF NOT EXISTS CONTRATO(
	idContrato INT NOT NULL AUTO_INCREMENT,
    valorEvento INT NOT NULL,
    qtdPessoa INT NOT NULL,
    idEvento INT NOT NULL,
    idCliente INT NOT NULL,
    CONSTRAINT CONTRATO_PK PRIMARY KEY(idContrato),
    CONSTRAINT EVENTO_FK FOREIGN KEY(idEvento)
		REFERENCES EVENTO(idEvento),
	CONSTRAINT CLIENTE_FK FOREIGN KEY(idCliente)
		REFERENCES CLIENTE(idCliente)
);

CREATE TABLE IF NOT EXISTS TRABALHA(
	idFuncionario INT NOT NULL,
    idEvento INT NOT NULL,
    CONSTRAINT FUNCIONARIO_FK FOREIGN KEY(idFuncionario)
		REFERENCES FUNCIONARIO(idFuncionario),
	CONSTRAINT EVENTO_FK_2 FOREIGN KEY(idEvento)
		REFERENCES EVENTO(idEvento)
);

CREATE TABLE IF NOT EXISTS USUARIO(
	nomeUsuario VARCHAR(50) NOT NULL,
    senhaUsuario VARCHAR(30) NOT NULL
);

INSERT INTO USUARIO(nomeUsuario , senhaUsuario) VALUES ('paulocerq', 'laranjamecanica123')


